# Лабораторная работа №3. Управляющие структуры

## Примеры из раздела 3.2

### Циклы for и while

In [2]:
# while можно использовать для формирования элементов массива
# пока n<10 прибавить к n единицу и распечатать значение:
n = 0
while n < 10
    n += 1
    println(n)
end


1
2
3
4
5
6
7
8
9
10


In [3]:
#= Другой пример демонстрирует использование while при работе со строковыми элементами массива, подставляя имя из массива в заданную строку приветствия и выводя
получившуюся конструкцию на экран=#
myfriends = ["Ted", "Robyn", "Barney", "Lily", "Marshall"]
i = 1
while i <= length(myfriends)
    friend = myfriends[i]
    println("Hi $friend, it's great to see you!")
    i += 1
end

Hi Ted, it's great to see you!
Hi Robyn, it's great to see you!
Hi Barney, it's great to see you!
Hi Lily, it's great to see you!
Hi Marshall, it's great to see you!


In [4]:
#Рассмотренные выше примеры, но с использованием цикла for:
for n in 1:2:10
println(n)
end


1
3
5
7
9


In [5]:
myfriends = ["Ted", "Robyn", "Barney", "Lily", "Marshall"]
for friend in myfriends
    println("Hi $friend, it's great to see you!")
end

Hi Ted, it's great to see you!
Hi Robyn, it's great to see you!
Hi Barney, it's great to see you!
Hi Lily, it's great to see you!
Hi Marshall, it's great to see you!


In [10]:
#Пример использования цикла for для создания двумерного массива, в котором значение каждой записи является суммой индексов строки и столбца:
# инициализация массива m x n из нулей:
m, n = 5, 5
A = fill(0, (m, n))
# формирование массива, в котором значение каждой записи
# является суммой индексов строки и столбца:
for i in 1:m
for j in 1:n
    A[i, j] = i + j
end
end
A

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [11]:
# Другая реализация этого же примера:
# инициализация массива m x n из нулей:B = fill(0, (m, n))
B = fill(0, (m, n))
for i in 1:m, j in 1:n
    B[i, j] = i + j
end
B

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [12]:
# Ещё одна реализация этого же примера:
C = [i + j for i in 1:m, j in 1:n]
C

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

### Условные выражения

In [16]:
# Например, пусть для заданного числа 𝑁 требуется вывести слово «Fizz», если 𝑁 делится на 3, «Buzz», если 𝑁 делится на 5, и «FizzBuzz», если 𝑁 делится на 3 и 5:
# используем `&&` для реализации операции "AND"
# операция % вычисляет остаток от деления
N = 15
if (N % 3 == 0) && (N % 5 == 0)
println("FizzBuzz")
elseif N % 3 == 0
println("Fizz")
elseif N % 5 == 0
println("Buzz")
else
println(N)
end

FizzBuzz


In [19]:
# Синтаксис условных выражений с тернарными операторами:
x = 5
y = 10
(x > y) ? x : y

10

###  Функции

In [23]:
#Julia дает нам несколько разных способов написать функцию. Первый требует ключевых слов function и end:
function sayhi(name)
    println("Hi $name, it's great to see you!")
end
# функция возведения в квадрат:
function f(x)
    x^2
end
sayhi("Nastya")
f(9)

Hi Nastya, it's great to see you!


81

In [29]:
# В качестве альтернативы, можно объявить любую из выше определённых функций в одной строке:
sayhi2(name) = println("Hi $name, it's great to see you!")
f2(x) = x^2
sayhi("Nastya")
f(9)

Hi Nastya, it's great to see you!


81

In [30]:
# Наконец, можно объявить выше определённые функции как «анонимные»:
sayhi3 = name -> println("Hi $name, it's great to see you!")
f3 = x -> x^2
sayhi("Nastya")
f(9)

Hi Nastya, it's great to see you!


81

In [32]:
#=По соглашению в Julia функции, сопровождаемые восклицательным знаком, изменяют
свое содержимое, а функции без восклицательного знака не делают этого.
Например, сравните результат применения sort и sort!:=#
# задаём массив v:
v = [3, 5, 2]
sort(v)
v


3-element Vector{Int64}:
 3
 5
 2

In [33]:
sort!(v)
v


3-element Vector{Int64}:
 2
 3
 5

In [35]:
map(f, [1, 2, 3])

3-element Vector{Int64}:
 1
 4
 9

In [36]:
map(x -> x^3, [1, 2, 3])


3-element Vector{Int64}:
  1
  8
 27

In [37]:
f(x) = x^2
broadcast(f, [1, 2, 3])

3-element Vector{Int64}:
 1
 4
 9

In [38]:
f.([1, 2, 3])

3-element Vector{Int64}:
 1
 4
 9

In [39]:
# Задаём матрицу A:
A = [i + 3*j for j in 0:2, i in 1:3]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [40]:
# Вызываем функцию f возведения в квадрат
f(A)


3×3 Matrix{Int64}:
  30   36   42
  66   81   96
 102  126  150

In [41]:
B = f.(A)


3×3 Matrix{Int64}:
  1   4   9
 16  25  36
 49  64  81

In [42]:
A .+ 2 .* f.(A) ./ A

3×3 Matrix{Float64}:
  3.0   6.0   9.0
 12.0  15.0  18.0
 21.0  24.0  27.0

In [43]:
@. A + 2 * f(A) / A


3×3 Matrix{Float64}:
  3.0   6.0   9.0
 12.0  15.0  18.0
 21.0  24.0  27.0

In [44]:
broadcast(x -> x + 2 * f(x) / x, A)

3×3 Matrix{Float64}:
  3.0   6.0   9.0
 12.0  15.0  18.0
 21.0  24.0  27.0

### Сторонние библиотеки (пакеты) в Julia

In [48]:
import Pkg
Pkg.add("Example")
Pkg.add("Colors")
using Colors
palette = distinguishable_colors(100)
rand(palette, 3, 3)

   Resolving package versions...
  No Changes to `C:\Users\noname\.julia\environments\v1.10\Project.toml`
  No Changes to `C:\Users\noname\.julia\environments\v1.10\Manifest.toml`
   Resolving package versions...
  No Changes to `C:\Users\noname\.julia\environments\v1.10\Project.toml`
  No Changes to `C:\Users\noname\.julia\environments\v1.10\Manifest.toml`


## Самостоятельная работа

### Задание 1. Используя циклы while и for выведите на экран целые числа от 1 до 100 и напечатайте их квадраты

In [52]:
n = 0
while n < 100
    n += 1
    print(n, "^2 = ", n*n, " | ")
end

1^2 = 1 | 2^2 = 4 | 3^2 = 9 | 4^2 = 16 | 5^2 = 25 | 6^2 = 36 | 7^2 = 49 | 8^2 = 64 | 9^2 = 81 | 10^2 = 100 | 11^2 = 121 | 12^2 = 144 | 13^2 = 169 | 14^2 = 196 | 15^2 = 225 | 16^2 = 256 | 17^2 = 289 | 18^2 = 324 | 19^2 = 361 | 20^2 = 400 | 21^2 = 441 | 22^2 = 484 | 23^2 = 529 | 24^2 = 576 | 25^2 = 625 | 26^2 = 676 | 27^2 = 729 | 28^2 = 784 | 29^2 = 841 | 30^2 = 900 | 31^2 = 961 | 32^2 = 1024 | 33^2 = 1089 | 34^2 = 1156 | 35^2 = 1225 | 36^2 = 1296 | 37^2 = 1369 | 38^2 = 1444 | 39^2 = 1521 | 40^2 = 1600 | 41^2 = 1681 | 42^2 = 1764 | 43^2 = 1849 | 44^2 = 1936 | 45^2 = 2025 | 46^2 = 2116 | 47^2 = 2209 | 48^2 = 2304 | 49^2 = 2401 | 50^2 = 2500 | 51^2 = 2601 | 52^2 = 2704 | 53^2 = 2809 | 54^2 = 2916 | 55^2 = 3025 | 56^2 = 3136 | 57^2 = 3249 | 58^2 = 3364 | 59^2 = 3481 | 60^2 = 3600 | 61^2 = 3721 | 62^2 = 3844 | 63^2 = 3969 | 64^2 = 4096 | 65^2 = 4225 | 66^2 = 4356 | 67^2 = 4489 | 68^2 = 4624 | 69^2 = 4761 | 70^2 = 4900 | 71^2 = 5041 | 72^2 = 5184 | 73^2 = 5329 | 74^2 = 5476 | 75^2 = 5625 | 76

In [55]:
for n in 1:1:100
    print(n, "^2 = ", n*n, " | ")
end

1^2 = 1 | 2^2 = 4 | 3^2 = 9 | 4^2 = 16 | 5^2 = 25 | 6^2 = 36 | 7^2 = 49 | 8^2 = 64 | 9^2 = 81 | 10^2 = 100 | 11^2 = 121 | 12^2 = 144 | 13^2 = 169 | 14^2 = 196 | 15^2 = 225 | 16^2 = 256 | 17^2 = 289 | 18^2 = 324 | 19^2 = 361 | 20^2 = 400 | 21^2 = 441 | 22^2 = 484 | 23^2 = 529 | 24^2 = 576 | 25^2 = 625 | 26^2 = 676 | 27^2 = 729 | 28^2 = 784 | 29^2 = 841 | 30^2 = 900 | 31^2 = 961 | 32^2 = 1024 | 33^2 = 1089 | 34^2 = 1156 | 35^2 = 1225 | 36^2 = 1296 | 37^2 = 1369 | 38^2 = 1444 | 39^2 = 1521 | 40^2 = 1600 | 41^2 = 1681 | 42^2 = 1764 | 43^2 = 1849 | 44^2 = 1936 | 45^2 = 2025 | 46^2 = 2116 | 47^2 = 2209 | 48^2 = 2304 | 49^2 = 2401 | 50^2 = 2500 | 51^2 = 2601 | 52^2 = 2704 | 53^2 = 2809 | 54^2 = 2916 | 55^2 = 3025 | 56^2 = 3136 | 57^2 = 3249 | 58^2 = 3364 | 59^2 = 3481 | 60^2 = 3600 | 61^2 = 3721 | 62^2 = 3844 | 63^2 = 3969 | 64^2 = 4096 | 65^2 = 4225 | 66^2 = 4356 | 67^2 = 4489 | 68^2 = 4624 | 69^2 = 4761 | 70^2 = 4900 | 71^2 = 5041 | 72^2 = 5184 | 73^2 = 5329 | 74^2 = 5476 | 75^2 = 5625 | 76

### Задание 1. Используя циклы while и for создайте словарь squares, который будет содержать целые числа в качестве ключей и квадраты в качестве их пар-значений

In [57]:
squares = Dict()
n = 0
while n<10
    n += 1
    squares[n] = n*n
end
pairs(squares)

Dict{Any, Any} with 10 entries:
  5  => 25
  4  => 16
  6  => 36
  7  => 49
  2  => 4
  10 => 100
  9  => 81
  8  => 64
  3  => 9
  1  => 1

In [58]:
for n in 1:10
    squares[n] = n*n
end
pairs(squares)

Dict{Any, Any} with 10 entries:
  5  => 25
  4  => 16
  6  => 36
  7  => 49
  2  => 4
  10 => 100
  9  => 81
  8  => 64
  3  => 9
  1  => 1

### Задание 1. Используя циклы while и for создайте массив squares_arr, содержащий квадраты всех чисел от 1 до 100

In [76]:
squares_arr=[]
n = 0
while n<100
    n += 1
    push!(squares_arr, [n*n])
end
print(squares_arr)

Any[[1], [4], [9], [16], [25], [36], [49], [64], [81], [100], [121], [144], [169], [196], [225], [256], [289], [324], [361], [400], [441], [484], [529], [576], [625], [676], [729], [784], [841], [900], [961], [1024], [1089], [1156], [1225], [1296], [1369], [1444], [1521], [1600], [1681], [1764], [1849], [1936], [2025], [2116], [2209], [2304], [2401], [2500], [2601], [2704], [2809], [2916], [3025], [3136], [3249], [3364], [3481], [3600], [3721], [3844], [3969], [4096], [4225], [4356], [4489], [4624], [4761], [4900], [5041], [5184], [5329], [5476], [5625], [5776], [5929], [6084], [6241], [6400], [6561], [6724], [6889], [7056], [7225], [7396], [7569], [7744], [7921], [8100], [8281], [8464], [8649], [8836], [9025], [9216], [9409], [9604], [9801], [10000]]

In [79]:
squares_arr_2 = [i*i for i in 1:100]
print(squares_arr_2)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801, 10000]

### Задание 2. Напишите условный оператор, который печатает число, если число чётное, и строку «нечётное», если число нечётное. Перепишите код, используя тернарный оператор.

In [80]:
N=1
if N % 2 == 0
    print(N)
else
    print("нечётное")
end

нечётное

In [83]:
N % 2 == 0 ? print(N) : print("нечётное")

нечётное

### Задание 3. Напишите функцию add_one, которая добавляет 1 к своему входу.

In [86]:
function add_one(N)
    N = N + 1
    println(N)
end
add_one(10)

11


### Задание 4. Используйте map() или broadcast() для задания матрицы 𝐴, каждый элемент которой увеличивается на единицу по сравнению с предыдущим.

In [91]:
# Задаём матрицу A:
A = [i + j for j in 0:4, i in 0:4]


5×5 Matrix{Int64}:
 0  1  2  3  4
 1  2  3  4  5
 2  3  4  5  6
 3  4  5  6  7
 4  5  6  7  8

In [93]:
map(x -> x+1, A)

5×5 Matrix{Int64}:
 1  2  3  4  5
 2  3  4  5  6
 3  4  5  6  7
 4  5  6  7  8
 5  6  7  8  9

### Задание 5. Задайте матрицу 𝐴 следующего вида (1 1 3; 5 2 6; -2 -1 -3). Найдите 𝐴^3. Замените третий столбец матрицы 𝐴 на сумму второго и третьего столбцов.

In [109]:
# ЗАдаем матрицу А
A = [1 1 3; 5 2 6; -2 -1 -3]

3×3 Matrix{Int64}:
  1   1   3
  5   2   6
 -2  -1  -3

In [99]:
f(n)=n^3
f(A)

3×3 Matrix{Int64}:
 0  0  0
 0  0  0
 0  0  0

In [110]:
for i in 1:3
    A[i,3]=A[i,2]+A[i,1] 
end       
A

3×3 Matrix{Int64}:
  1   1   2
  5   2   7
 -2  -1  -3

### Задание 6. Создайте матрицу B с элементами 𝐵𝑖1 = 10, 𝐵𝑖2 = −10, 𝐵𝑖3 = 10, 𝑖 = 1, 2, … , 15. Вычислите матрицу 𝐶 = 𝐵^𝑇*𝐵.

In [121]:
# ЗАдаем матрицу B
B = [j%2==1 ? x=10 : x=-10 for i in 1:15,j in 1:3]
B

15×3 Matrix{Int64}:
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10

In [126]:
C=B'*B

3×3 Matrix{Int64}:
  1500  -1500   1500
 -1500   1500  -1500
  1500  -1500   1500

### Задание 7. Создайте матрицу 𝑍 размерности 6 × 6, все элементы которой равны нулю, и матрицу 𝐸, все элементы которой равны 1. Используя цикл while или for и закономерности расположения элементов, создайте следующие матрицы размерности 6 × 6:

In [134]:
Z = zeros(6,6)
E = ones(6,6)

Z1 = copy(Z)
for i in 1:6, j in 1:6
    if abs(i-j) == 1
        Z1[i,j]=Z[i,j]+E[i,j]
    end
    Z1[i,j] |> Int64
end
Z1

6×6 Matrix{Float64}:
 0.0  1.0  0.0  0.0  0.0  0.0
 1.0  0.0  1.0  0.0  0.0  0.0
 0.0  1.0  0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0  0.0  1.0
 0.0  0.0  0.0  0.0  1.0  0.0

In [136]:
Z2 = copy(Z)
for i in 1:6, j in 1:6
    if abs(i-j) == 2 || i == j
        Z2[i,j]=Z[i,j]+E[i,j]
    end
    Z2[i,j] |> Int64
end
Z2

6×6 Matrix{Float64}:
 1.0  0.0  1.0  0.0  0.0  0.0
 0.0  1.0  0.0  1.0  0.0  0.0
 1.0  0.0  1.0  0.0  1.0  0.0
 0.0  1.0  0.0  1.0  0.0  1.0
 0.0  0.0  1.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0  0.0  1.0

In [137]:
Z3 = copy(Z)
for i in 1:6, j in 1:6
    if i+j == 5 || i+j == 7 || i+j == 9 
        Z3[i,j]=Z[i,j]+E[i,j]
    end
    Z3[i,j] |> Int64
end
Z3

6×6 Matrix{Float64}:
 0.0  0.0  0.0  1.0  0.0  1.0
 0.0  0.0  1.0  0.0  1.0  0.0
 0.0  1.0  0.0  1.0  0.0  1.0
 1.0  0.0  1.0  0.0  1.0  0.0
 0.0  1.0  0.0  1.0  0.0  0.0
 1.0  0.0  1.0  0.0  0.0  0.0

In [139]:
Z4 = copy(Z)
for i in 1:6, j in 1:6
    if (i+j) % 2 == 0 
        Z4[i,j]=Z[i,j]+E[i,j]
    end
    Z4[i,j] |> Int64
end
Z4

6×6 Matrix{Float64}:
 1.0  0.0  1.0  0.0  1.0  0.0
 0.0  1.0  0.0  1.0  0.0  1.0
 1.0  0.0  1.0  0.0  1.0  0.0
 0.0  1.0  0.0  1.0  0.0  1.0
 1.0  0.0  1.0  0.0  1.0  0.0
 0.0  1.0  0.0  1.0  0.0  1.0

### Задание 8. В языке R есть функция outer(). Фактически, это матричное умножение с возможностью изменить применяемую операцию (например, заменить произведение на сложение или возведение в степень). Подпункт 1 (см.в файле лр)

In [148]:
function outer(x,y,operation)
    return [operation(xi, yi) for xi in x, yi in y]
end

outer (generic function with 1 method)

### Задание 8. В языке R есть функция outer(). Фактически, это матричное умножение с возможностью изменить применяемую операцию (например, заменить произведение на сложение или возведение в степень). Подпункт 2 (см.в файле лр)

In [149]:
A1 = outer(0:4, 0:4, +)

5×5 Matrix{Int64}:
 0  1  2  3  4
 1  2  3  4  5
 2  3  4  5  6
 3  4  5  6  7
 4  5  6  7  8

In [151]:
A2 = [y == 1 ? x : x^y for x in 0:4, y in 1:5]

5×5 Matrix{Int64}:
 0   0   0    0     0
 1   1   1    1     1
 2   4   8   16    32
 3   9  27   81   243
 4  16  64  256  1024

In [152]:
A3 = outer(0:4, 0:4, (x,y) -> mod(x+y,5))

5×5 Matrix{Int64}:
 0  1  2  3  4
 1  2  3  4  0
 2  3  4  0  1
 3  4  0  1  2
 4  0  1  2  3

In [153]:
A4 = outer(0:9, 0:9, (x,y) -> mod(x+y,10))

10×10 Matrix{Int64}:
 0  1  2  3  4  5  6  7  8  9
 1  2  3  4  5  6  7  8  9  0
 2  3  4  5  6  7  8  9  0  1
 3  4  5  6  7  8  9  0  1  2
 4  5  6  7  8  9  0  1  2  3
 5  6  7  8  9  0  1  2  3  4
 6  7  8  9  0  1  2  3  4  5
 7  8  9  0  1  2  3  4  5  6
 8  9  0  1  2  3  4  5  6  7
 9  0  1  2  3  4  5  6  7  8

In [154]:
A5 = outer(0:8, 0:8, (x,y) -> mod(x-y,9))

9×9 Matrix{Int64}:
 0  8  7  6  5  4  3  2  1
 1  0  8  7  6  5  4  3  2
 2  1  0  8  7  6  5  4  3
 3  2  1  0  8  7  6  5  4
 4  3  2  1  0  8  7  6  5
 5  4  3  2  1  0  8  7  6
 6  5  4  3  2  1  0  8  7
 7  6  5  4  3  2  1  0  8
 8  7  6  5  4  3  2  1  0

### Задание 9. Решите следующую систему линейных уравнений с 5 неизвестными

In [192]:
A = [1 2 3 4 5; 2 1 2 3 4; 3 2 1 2 3; 4 3 2 1 2; 5 4 3 2 1]
B = [7, -1, -3, 5, -6]

X = A \ B  
for i in 1:5
    println("X$i = ", X[i], "\n" )
end

X1 = -3.916666666666667

X2 = 3.0000000000000013

X3 = 5.0

X4 = -9.500000000000002

X5 = 5.583333333333335



### Задание 10. Создайте матрицу 𝑀 размерности 6 × 10, элементами которой являются целые числа, выбранные случайным образом с повторениями из совокупности 1, 2, … , 10. 


In [213]:
M = rand(1:10, 6, 10)


6×10 Matrix{Int64}:
 10   6  3  8  7   4  5   7  3  4
 10   8  8  6  4  10  1  10  4  5
  9   1  9  7  3   3  3   4  1  5
 10   3  2  3  8  10  4   7  5  5
  7  10  3  7  9   6  5   8  5  3
 10   1  1  8  7   1  1   9  2  7

- Найдите число элементов в каждой строке матрицы 𝑀, которые больше числа 𝑁 (например, 𝑁 = 4).

In [214]:
N = 4
res = sum(M .> N, dims=2)
println(res)

[6; 7; 4; 6; 8; 5;;]


- Определите, в каких строках матрицы 𝑀 число 𝑀(например,𝑀 = 7) встречается
ровно 2 раза?


In [215]:
M_value = 7
rows_res = findall(x -> count(==(M_value), x) == 2, eachrow(M))
println(rows_res)

[1, 5, 6]


- Определите все пары столбцов матрицы 𝑀, сумма элементов которых больше 𝐾
(например, 𝐾 = 75).