# Лабораторная работа №1. Примеры из раздела 1.3.3.

In [20]:
typeof(3), typeof(3.5), typeof(3/3.5), typeof(sqrt(3+4im)), typeof(pi)

(Int64, Float64, Float64, ComplexF64, Irrational{:π})

In [23]:
1.0/0.0, 1.0/(-0.0), 0.0/0.0

(Inf, -Inf, NaN)

In [24]:
typeof(1.0/0.0), typeof(1.0/(-0.0)), typeof(0.0/0.0)

(Float64, Float64, Float64)

In [26]:
for T in [Int8,Int16,Int32,Int64,Int128,UInt8,UInt16,UInt32,UInt64,UInt128]
println("$(lpad(T,7)): [$(typemin(T)),$(typemax(T))]")
end

   Int8: [-128,127]
  Int16: [-32768,32767]
  Int32: [-2147483648,2147483647]
  Int64: [-9223372036854775808,9223372036854775807]
 Int128: [-170141183460469231731687303715884105728,170141183460469231731687303715884105727]
  UInt8: [0,255]
 UInt16: [0,65535]
 UInt32: [0,4294967295]
 UInt64: [0,18446744073709551615]
UInt128: [0,340282366920938463463374607431768211455]


In [27]:
Int64(2.0), Char(2), typeof(Char(2))

(2, '\x02', Char)

In [30]:
convert(Int64, 2.0), convert(Char,2)

(2, '\x02')

In [31]:
2.0 |> Int64

2

In [32]:
Bool(1), Bool(0)

(true, false)

In [35]:
typeof(promote(Int8(1), Float16(4.5), Float32(4.1)))

Tuple{Float32, Float32, Float32}

In [36]:
function f(x)
    x^2
end
f(4)

16

In [38]:
g(x)=x^2
g(8)

64

In [43]:
a = [4 7 6]
b = [1, 2, 3]
a[2], b[2]

(7, 2)

In [46]:
a = 1; b = 2; c = 3; d = 4
Am = [a b; c d]

2×2 Matrix{Int64}:
 1  2
 3  4

In [47]:
Am[1,1], Am[1,2], Am[2,1], Am[2,2]

(1, 2, 3, 4)

In [49]:
aa = [1 2]
AA = [1 2; 3 4]
aa*AA*aa'

1×1 Matrix{Int64}:
 27

In [50]:
aa, AA, aa'

([1 2], [1 2; 3 4], [1; 2;;])

# Самостоятельная работа

## Задание 1. 
### Изучите документацию по основным функциям Julia для  чтения / записи / вывода информации на экран: read(), readline(), readlines(), readdlm(), print(), println(), show(), write(). Приведите свои примеры их использования, поясняя особенности их применения.

In [53]:
?read()

```
read(io::IO, T)
```

Read a single value of type `T` from `io`, in canonical binary representation.

Note that Julia does not convert the endianness for you. Use [`ntoh`](@ref) or [`ltoh`](@ref) for this purpose.

```
read(io::IO, String)
```

Read the entirety of `io`, as a `String` (see also [`readchomp`](@ref)).

# Examples

```jldoctest
julia> io = IOBuffer("JuliaLang is a GitHub organization");

julia> read(io, Char)
'J': ASCII/Unicode U+004A (category Lu: Letter, uppercase)

julia> io = IOBuffer("JuliaLang is a GitHub organization");

julia> read(io, String)
"JuliaLang is a GitHub organization"
```

---

```
read(filename::AbstractString)
```

Read the entire contents of a file as a `Vector{UInt8}`.

```
read(filename::AbstractString, String)
```

Read the entire contents of a file as a string.

```
read(filename::AbstractString, args...)
```

Open a file and read its contents. `args` is passed to `read`: this is equivalent to `open(io->read(io, args...), filename)`.

---

```
read(s::IO, nb=typemax(Int))
```

Read at most `nb` bytes from `s`, returning a `Vector{UInt8}` of the bytes read.

---

```
read(s::IOStream, nb::Integer; all=true)
```

Read at most `nb` bytes from `s`, returning a `Vector{UInt8}` of the bytes read.

If `all` is `true` (the default), this function will block repeatedly trying to read all requested bytes, until an error or end-of-file occurs. If `all` is `false`, at most one `read` call is performed, and the amount of data returned is device-dependent. Note that not all stream types support the `all` option.

---

```
read(command::Cmd)
```

Run `command` and return the resulting output as an array of bytes.

---

```
read(command::Cmd, String)
```

Run `command` and return the resulting output as a `String`.


In [57]:
task1 = IOBuffer("It is the first task today")
read(task1, String)

"It is the first task today"

In [58]:
?readline()

```
readline(io::IO=stdin; keep::Bool=false)
readline(filename::AbstractString; keep::Bool=false)
```

Read a single line of text from the given I/O stream or file (defaults to `stdin`). When reading from a file, the text is assumed to be encoded in UTF-8. Lines in the input end with `'\n'` or `"\r\n"` or the end of an input stream. When `keep` is false (as it is by default), these trailing newline characters are removed from the line before it is returned. When `keep` is true, they are returned as part of the line.

# Examples

```jldoctest
julia> write("my_file.txt", "JuliaLang is a GitHub organization.\nIt has many members.\n");

julia> readline("my_file.txt")
"JuliaLang is a GitHub organization."

julia> readline("my_file.txt", keep=true)
"JuliaLang is a GitHub organization.\n"

julia> rm("my_file.txt")
```

```julia-repl
julia> print("Enter your name: ")
Enter your name:

julia> your_name = readline()
Logan
"Logan"
```


In [83]:
write("task1.txt", "This is too hard.\nHelp me")
readlines("task1.txt")

2-element Vector{String}:
 "This is too hard."
 "Help me"

In [62]:
print("Who ar you?")
you = readline()

Who ar you?

stdin>  Kolobok


"Kolobok"

In [63]:
?readlines()

```
readlines(io::IO=stdin; keep::Bool=false)
readlines(filename::AbstractString; keep::Bool=false)
```

Read all lines of an I/O stream or a file as a vector of strings. Behavior is equivalent to saving the result of reading [`readline`](@ref) repeatedly with the same arguments and saving the resulting lines as a vector of strings.  See also [`eachline`](@ref) to iterate over the lines without reading them all at once.

# Examples

```jldoctest
julia> write("my_file.txt", "JuliaLang is a GitHub organization.\nIt has many members.\n");

julia> readlines("my_file.txt")
2-element Vector{String}:
 "JuliaLang is a GitHub organization."
 "It has many members."

julia> readlines("my_file.txt", keep=true)
2-element Vector{String}:
 "JuliaLang is a GitHub organization.\n"
 "It has many members.\n"

julia> rm("my_file.txt")
```


In [64]:
write("task1.txt", "This is too hard.\nHelp me")
readlines("task1.txt")

2-element Vector{String}:
 "This is too hard."
 "Help me"

In [67]:
?readdlm

search: readdir

Couldn't find readdlm
Perhaps you meant readdir, read, read!, real or readchomp


No documentation found.

Binding `readdlm` does not exist.


In [68]:
?readdlm()

No documentation found.

Binding `readdlm` does not exist.


In [69]:
?print()

```
print([io::IO], xs...)
```

Write to `io` (or to the default output stream [`stdout`](@ref) if `io` is not given) a canonical (un-decorated) text representation. The representation used by `print` includes minimal formatting and tries to avoid Julia-specific details.

`print` falls back to calling `show`, so most types should just define `show`. Define `print` if your type has a separate "plain" representation. For example, `show` displays strings with quotes, and `print` displays strings without quotes.

See also [`println`](@ref), [`string`](@ref), [`printstyled`](@ref).

# Examples

```jldoctest
julia> print("Hello World!")
Hello World!
julia> io = IOBuffer();

julia> print(io, "Hello", ' ', :World!)

julia> String(take!(io))
"Hello World!"
```


In [70]:
print("Your name is too strong in pronunciation")

Your name is too strong in pronunciation

In [72]:
name = "Nastya"
print(name, ", good morning!")

Nastya, good morning!

In [73]:
?println()

```
println([io::IO], xs...)
```

Print (using [`print`](@ref)) `xs` to `io` followed by a newline. If `io` is not supplied, prints to the default output stream [`stdout`](@ref).

See also [`printstyled`](@ref) to add colors etc.

# Examples

```jldoctest
julia> println("Hello, world")
Hello, world

julia> io = IOBuffer();

julia> println(io, "Hello", ',', " world.")

julia> String(take!(io))
"Hello, world.\n"
```


In [79]:
print("hello")
print("there is no space")
println("it's joke")
println("yeah")
print("tratata")

hellothere is no spaceit's joke
yeah
tratata

In [80]:
?show()

```
show([io::IO = stdout], x)
```

Write a text representation of a value `x` to the output stream `io`. New types `T` should overload `show(io::IO, x::T)`. The representation used by `show` generally includes Julia-specific formatting and type information, and should be parseable Julia code when possible.

[`repr`](@ref) returns the output of `show` as a string.

For a more verbose human-readable text output for objects of type `T`, define `show(io::IO, ::MIME"text/plain", ::T)` in addition. Checking the `:compact` [`IOContext`](@ref) key (often checked as `get(io, :compact, false)::Bool`) of `io` in such methods is recommended, since some containers show their elements by calling this method with `:compact => true`.

See also [`print`](@ref), which writes un-decorated representations.

# Examples

```jldoctest
julia> show("Hello World!")
"Hello World!"
julia> print("Hello World!")
Hello World!
```

---

```
show(io::IO, mime, x)
```

The [`display`](@ref) functions ultimately call `show` in order to write an object `x` as a given `mime` type to a given I/O stream `io` (usually a memory buffer), if possible. In order to provide a rich multimedia representation of a user-defined type `T`, it is only necessary to define a new `show` method for `T`, via: `show(io, ::MIME"mime", x::T) = ...`, where `mime` is a MIME-type string and the function body calls [`write`](@ref) (or similar) to write that representation of `x` to `io`. (Note that the `MIME""` notation only supports literal strings; to construct `MIME` types in a more flexible manner use `MIME{Symbol("")}`.)

For example, if you define a `MyImage` type and know how to write it to a PNG file, you could define a function `show(io, ::MIME"image/png", x::MyImage) = ...` to allow your images to be displayed on any PNG-capable `AbstractDisplay` (such as IJulia). As usual, be sure to `import Base.show` in order to add new methods to the built-in Julia function `show`.

Technically, the `MIME"mime"` macro defines a singleton type for the given `mime` string, which allows us to exploit Julia's dispatch mechanisms in determining how to display objects of any given type.

The default MIME type is `MIME"text/plain"`. There is a fallback definition for `text/plain` output that calls `show` with 2 arguments, so it is not always necessary to add a method for that case. If a type benefits from custom human-readable output though, `show(::IO, ::MIME"text/plain", ::T)` should be defined. For example, the `Day` type uses `1 day` as the output for the `text/plain` MIME type, and `Day(1)` as the output of 2-argument `show`.

# Examples

```jldoctest
julia> struct Day
           n::Int
       end

julia> Base.show(io::IO, ::MIME"text/plain", d::Day) = print(io, d.n, " day")

julia> Day(1)
1 day
```

Container types generally implement 3-argument `show` by calling `show(io, MIME"text/plain"(), x)` for elements `x`, with `:compact => true` set in an [`IOContext`](@ref) passed as the first argument.


In [81]:
show("what a beautiful day!")

"what a beautiful day!"

In [82]:
?write()

```
write(io::IO, x)
```

Write the canonical binary representation of a value to the given I/O stream or file. Return the number of bytes written into the stream. See also [`print`](@ref) to write a text representation (with an encoding that may depend upon `io`).

The endianness of the written value depends on the endianness of the host system. Convert to/from a fixed endianness when writing/reading (e.g. using  [`htol`](@ref) and [`ltoh`](@ref)) to get results that are consistent across platforms.

You can write multiple values with the same `write` call. i.e. the following are equivalent:

```
write(io, x, y...)
write(io, x) + write(io, y...)
```

# Examples

Consistent serialization:

```jldoctest
julia> fname = tempname(); # random temporary filename

julia> open(fname,"w") do f
           # Make sure we write 64bit integer in little-endian byte order
           write(f,htol(Int64(42)))
       end
8

julia> open(fname,"r") do f
           # Convert back to host byte order and host integer type
           Int(ltoh(read(f,Int64)))
       end
42
```

Merging write calls:

```jldoctest
julia> io = IOBuffer();

julia> write(io, "JuliaLang is a GitHub organization.", " It has many members.")
56

julia> String(take!(io))
"JuliaLang is a GitHub organization. It has many members."

julia> write(io, "Sometimes those members") + write(io, " write documentation.")
44

julia> String(take!(io))
"Sometimes those members write documentation."
```

User-defined plain-data types without `write` methods can be written when wrapped in a `Ref`:

```jldoctest
julia> struct MyStruct; x::Float64; end

julia> io = IOBuffer()
IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=0, maxsize=Inf, ptr=1, mark=-1)

julia> write(io, Ref(MyStruct(42.0)))
8

julia> seekstart(io); read!(io, Ref(MyStruct(NaN)))
Base.RefValue{MyStruct}(MyStruct(42.0))
```

---

```
write(filename::AbstractString, content)
```

Write the canonical binary representation of `content` to a file, which will be created if it does not exist yet or overwritten if it does exist.

Return the number of bytes written into the file.


## Задание 2. 
### Изучите документацию по функции parse(). Приведите свои примеры её использования, поясняя особенности её применения

In [84]:
?parse()

```
parse(type, str; base)
```

Parse a string as a number. For `Integer` types, a base can be specified (the default is 10). For floating-point types, the string is parsed as a decimal floating-point number.  `Complex` types are parsed from decimal strings of the form `"R±Iim"` as a `Complex(R,I)` of the requested type; `"i"` or `"j"` can also be used instead of `"im"`, and `"R"` or `"Iim"` are also permitted. If the string does not contain a valid number, an error is raised.

!!! compat "Julia 1.1"
    `parse(Bool, str)` requires at least Julia 1.1.


# Examples

```jldoctest
julia> parse(Int, "1234")
1234

julia> parse(Int, "1234", base = 5)
194

julia> parse(Int, "afc", base = 16)
2812

julia> parse(Float64, "1.2e-3")
0.0012

julia> parse(Complex{Float64}, "3.2e-1 + 4.5im")
0.32 + 4.5im
```

---

```
parse(::Type{Platform}, triplet::AbstractString)
```

Parses a string platform triplet back into a `Platform` object.


In [93]:
parse(Int64, "10")

10

In [94]:
convert(int64, "10")

LoadError: UndefVarError: `int64` not defined

## Задание 3.
### Изучите синтаксис Julia для базовых математических операций с разным типом переменных: сложение, вычитание, умножение, деление, возведение в степень, извлечение корня, сравнение, логические операции. Приведите свои примеры с пояснениями по особенностям их применения

In [97]:
plus = 1.0 + 2

3.0

In [98]:
minus = 1 - 2.0

-1.0

In [99]:
proizvedenie = 1 * 2.0

2.0

In [100]:
delenie = 1 / 2.0

0.5

In [102]:
delenie_po_modulu = 10 % 3

1

In [103]:
delenie_nacelo = 10 ÷ 3

3

In [110]:
div(10, 3) # delenie nacelo

3

In [105]:
sqrtt = √9

3.0

In [107]:
sqrt(9) # извлечение корня

3.0

In [108]:
pow = 3^2 

9

In [109]:
drobi = 10 // 2

5//1

In [120]:
A = [ 0 0; 0 0]

2×2 Matrix{Int64}:
 0  0
 0  0

In [121]:
B = [1 1; 1 1]

2×2 Matrix{Int64}:
 1  1
 1  1

In [126]:
C = A+B

2×2 Matrix{Int64}:
 1  1
 1  1

In [128]:
D = A - B 

2×2 Matrix{Int64}:
 -1  -1
 -1  -1

In [133]:
E = A * B # умножение матриц

2×2 Matrix{Int64}:
 0  0
 0  0

In [138]:
B1 = [10 10 10; 10 10 10]
E1 = B * B1

2×3 Matrix{Int64}:
 20  20  20
 20  20  20

In [141]:
B1

2×3 Matrix{Int64}:
 10  10  10
 10  10  10

In [140]:
BB = B1'

3×2 adjoint(::Matrix{Int64}) with eltype Int64:
 10  10
 10  10
 10  10

In [131]:
G = B*10 # умножение на скаляр

2×2 Matrix{Int64}:
 10  10
 10  10